require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MapAuthorsController do

  # This should return the minimal set of attributes required to create a valid
  # MapAuthor. As you add validations to MapAuthor, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all map_authors as @map_authors" do
      map_author = MapAuthor.create! valid_attributes
      get :index
      assigns(:map_authors).should eq([map_author])
    end
  end

  describe "GET show" do
    it "assigns the requested map_author as @map_author" do
      map_author = MapAuthor.create! valid_attributes
      get :show, :id => map_author.id.to_s
      assigns(:map_author).should eq(map_author)
    end
  end

  describe "GET new" do
    it "assigns a new map_author as @map_author" do
      get :new
      assigns(:map_author).should be_a_new(MapAuthor)
    end
  end

  describe "GET edit" do
    it "assigns the requested map_author as @map_author" do
      map_author = MapAuthor.create! valid_attributes
      get :edit, :id => map_author.id.to_s
      assigns(:map_author).should eq(map_author)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MapAuthor" do
        expect {
          post :create, :map_author => valid_attributes
        }.to change(MapAuthor, :count).by(1)
      end

      it "assigns a newly created map_author as @map_author" do
        post :create, :map_author => valid_attributes
        assigns(:map_author).should be_a(MapAuthor)
        assigns(:map_author).should be_persisted
      end

      it "redirects to the created map_author" do
        post :create, :map_author => valid_attributes
        response.should redirect_to(MapAuthor.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved map_author as @map_author" do
        # Trigger the behavior that occurs when invalid params are submitted
        MapAuthor.any_instance.stub(:save).and_return(false)
        post :create, :map_author => {}
        assigns(:map_author).should be_a_new(MapAuthor)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MapAuthor.any_instance.stub(:save).and_return(false)
        post :create, :map_author => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested map_author" do
        map_author = MapAuthor.create! valid_attributes
        # Assuming there are no other map_authors in the database, this
        # specifies that the MapAuthor created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MapAuthor.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => map_author.id, :map_author => {'these' => 'params'}
      end

      it "assigns the requested map_author as @map_author" do
        map_author = MapAuthor.create! valid_attributes
        put :update, :id => map_author.id, :map_author => valid_attributes
        assigns(:map_author).should eq(map_author)
      end

      it "redirects to the map_author" do
        map_author = MapAuthor.create! valid_attributes
        put :update, :id => map_author.id, :map_author => valid_attributes
        response.should redirect_to(map_author)
      end
    end

    describe "with invalid params" do
      it "assigns the map_author as @map_author" do
        map_author = MapAuthor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MapAuthor.any_instance.stub(:save).and_return(false)
        put :update, :id => map_author.id.to_s, :map_author => {}
        assigns(:map_author).should eq(map_author)
      end

      it "re-renders the 'edit' template" do
        map_author = MapAuthor.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MapAuthor.any_instance.stub(:save).and_return(false)
        put :update, :id => map_author.id.to_s, :map_author => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested map_author" do
      map_author = MapAuthor.create! valid_attributes
      expect {
        delete :destroy, :id => map_author.id.to_s
      }.to change(MapAuthor, :count).by(-1)
    end

    it "redirects to the map_authors list" do
      map_author = MapAuthor.create! valid_attributes
      delete :destroy, :id => map_author.id.to_s
      response.should redirect_to(map_authors_url)
    end
  end

end
