require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubmissionCommentsController do

  # This should return the minimal set of attributes required to create a valid
  # SubmissionComment. As you add validations to SubmissionComment, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all submission_comments as @submission_comments" do
      submission_comment = SubmissionComment.create! valid_attributes
      get :index
      assigns(:submission_comments).should eq([submission_comment])
    end
  end

  describe "GET show" do
    it "assigns the requested submission_comment as @submission_comment" do
      submission_comment = SubmissionComment.create! valid_attributes
      get :show, :id => submission_comment.id.to_s
      assigns(:submission_comment).should eq(submission_comment)
    end
  end

  describe "GET new" do
    it "assigns a new submission_comment as @submission_comment" do
      get :new
      assigns(:submission_comment).should be_a_new(SubmissionComment)
    end
  end

  describe "GET edit" do
    it "assigns the requested submission_comment as @submission_comment" do
      submission_comment = SubmissionComment.create! valid_attributes
      get :edit, :id => submission_comment.id.to_s
      assigns(:submission_comment).should eq(submission_comment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SubmissionComment" do
        expect {
          post :create, :submission_comment => valid_attributes
        }.to change(SubmissionComment, :count).by(1)
      end

      it "assigns a newly created submission_comment as @submission_comment" do
        post :create, :submission_comment => valid_attributes
        assigns(:submission_comment).should be_a(SubmissionComment)
        assigns(:submission_comment).should be_persisted
      end

      it "redirects to the created submission_comment" do
        post :create, :submission_comment => valid_attributes
        response.should redirect_to(SubmissionComment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved submission_comment as @submission_comment" do
        # Trigger the behavior that occurs when invalid params are submitted
        SubmissionComment.any_instance.stub(:save).and_return(false)
        post :create, :submission_comment => {}
        assigns(:submission_comment).should be_a_new(SubmissionComment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SubmissionComment.any_instance.stub(:save).and_return(false)
        post :create, :submission_comment => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested submission_comment" do
        submission_comment = SubmissionComment.create! valid_attributes
        # Assuming there are no other submission_comments in the database, this
        # specifies that the SubmissionComment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SubmissionComment.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => submission_comment.id, :submission_comment => {'these' => 'params'}
      end

      it "assigns the requested submission_comment as @submission_comment" do
        submission_comment = SubmissionComment.create! valid_attributes
        put :update, :id => submission_comment.id, :submission_comment => valid_attributes
        assigns(:submission_comment).should eq(submission_comment)
      end

      it "redirects to the submission_comment" do
        submission_comment = SubmissionComment.create! valid_attributes
        put :update, :id => submission_comment.id, :submission_comment => valid_attributes
        response.should redirect_to(submission_comment)
      end
    end

    describe "with invalid params" do
      it "assigns the submission_comment as @submission_comment" do
        submission_comment = SubmissionComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SubmissionComment.any_instance.stub(:save).and_return(false)
        put :update, :id => submission_comment.id.to_s, :submission_comment => {}
        assigns(:submission_comment).should eq(submission_comment)
      end

      it "re-renders the 'edit' template" do
        submission_comment = SubmissionComment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SubmissionComment.any_instance.stub(:save).and_return(false)
        put :update, :id => submission_comment.id.to_s, :submission_comment => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested submission_comment" do
      submission_comment = SubmissionComment.create! valid_attributes
      expect {
        delete :destroy, :id => submission_comment.id.to_s
      }.to change(SubmissionComment, :count).by(-1)
    end

    it "redirects to the submission_comments list" do
      submission_comment = SubmissionComment.create! valid_attributes
      delete :destroy, :id => submission_comment.id.to_s
      response.should redirect_to(submission_comments_url)
    end
  end

end
